- name: Install Apache Web Server for redhat servers
  yum: pkg='{{ redhat_apache }}'  state=latest
  when: "ansible_os_family == 'RedHat'"
  notify: restart httpd 
- name: Install Apache server for debain servers
  apt: pkg='{{ debian_apache }}' state=latest
  when: "ansible_os_family == 'Debian'"
  notify: restart apache
