--- # Playbook to describe apt module
- hosts: ubuntu
  sudo: yes
  gather_facts: no
  tasks: 
  - name: Equivalen of apt-get update
    apt: update_cache=yes
  - name: Equivalent of apt-get upgrade
    apt: upgrade=dist
