--- #Playbook to describe the fetch module
- hosts: all
  sudo: yes
  gather_facts: yes
 
  tasks:
    - name: fetch the hosts file on web server to local ansible home
      fetch: src=/etc/hosts dest=/home/ansible/prefix-{{ ansible_hostname }} flat=yes
