--- #get_url module
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  
  tasks: 
   - name: Download a zip file to a certain location
     get_url: url=https://pkg.jenkins.io/redhat-stable/jenkins-2.107.3-1.1.noarch.rpm dest=/home/ansible/
