--- # Playbook to test the Loop functionality
- hosts: redhat
  sudo: yes
  gather_facts: no
  vars: 
    pkg:
     - telnet
     - lynx
     - elinks
  tasks: 
    - name: Add 3 users on all the redhat servers
      yum : name={{ pkg }} state=present
      with_items: "{{ pkg }}"
