--- #Describing the pause module
- hosts: apacheweb
  sudo: yes
  gather_facts: no 

  tasks: 
    - name: Installing httpd
      yum: pkg=httpd state=latest
    - name: Pause the playbook to check httpd installation status
      pause: 
        seconds: 3
    - name: install lynx browser
      yum: pkg=lynx state=latest
