--- # Describes shell module
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  
  tasks: 
   - name: Execute the shell commands remotely
     shell: /bin/uptime >> uptime.log
     args:
       chdir: /home/ansible/
       creates: uptime.log
