--- # Playbook for tags example
- hosts: appserver
  sudo: yes
  connection: ssh
  user: ansible
  gather_facts: no

  tasks: 
    - name: Install client software lynx and telnet
      yum: pkg={{ item }} state=latest
      with_items: 
        - lynx
        - telnet
      tags: 
        - packages
    - name: Verify if telnet was installed
      raw: yum list installed | grep telnet | date >> /tmp/pkg.log
      tags: always 
