--- #Unarchive the tar file
- hosts: apacheweb
  sudo: yes
  gather_facts: no

  tasks: 
   - name: Unarchive playbook tar file
     unarchive: src=/home/ansible/playbook.tar.gz dest=/home/ansible/abc
