--- #Playbook describes wait_for module
- hosts: apacheweb
  sudo: yes
  gather_facts: no

  tasks: 
   - name: Install tomcat
     action: yum name=tomcat state=latest
   - name: Wait for tomcat to start
     wait_for: 
       port: 8080
       state: started
   - name: Install Lynx
     yum: pkg=lynx state=latest
