--- # Testing the J2 Template Module
- hosts: appserver
  sudo: yes
  vars:
   userName: test
   userPassword: password
   connectionType: SFTP
  tasks:
    - name: Install the configuration file customized for the system
      template: src=test.conf.j2 dest=/home/ansible/ansible.conf owner=ansible group=ansible mode=0750
