--- #Installing the apache package and setting it up this is just a raw version
- hosts:  all
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: pkg
      prompt: Enter the package name
  tasks: 
    - name: Log the timestamp when the installation starts
      command: /usr/bin/date
      register: timestamp_start
    - debug: var=timestamp_start
    - name: Place default index file
      file: path=/var/www/html/index.html state=absent
      run_once: true
    - name: Install the apache web application
      yum: pkg=httpd state=installed
      notify:
        - start httpd
        - check httpd
    - name: Install the client-telnet software
      yum: pkg=telnet state=installed
    - name: Install the client-lynx software
      yum: pkg={{ pkg }} state=installed
    - name: Log the timestamp when the installation ends
      command: /usr/bin/date
      register: timestamp_stop
    - debug: var=timestamp_stop
    - debug: msg="{{ lookup('env','HOME') }} is the listed value"

  handlers: 
    - name: start httpd
      service: name=httpd.service state=started
    - name: check httpd
      command: systemctl status httpd
      register: result
    - debug: var=result
